spring.application.name=ship-api

# 내장 H2 데이터베이스 사용 (외부 EC2 타임아웃 / OOM 100% 해소, 0초 반응속도)
spring.datasource.url=jdbc:h2:mem:ulleung_ticket;MODE=MySQL;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080
